version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container_v2
    environment:
      POSTGRES_DB: Parts_db
      POSTGRES_USER: adminMBD
      POSTGRES_PASSWORD: jakub123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_container_v2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_NAME: Parts_db
      DB_USER: adminMBD
      DB_PASSWORD: jakub123

volumes:
  postgres_data: